#
version: '3.8'

services:
    mongodb_tickets:
        image: mongo:7
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'root'
            MONGO_INITDB_ROOT_PASSWORD: 'password'
            MONGO_INITDB_DATABASE: 'tickets'
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongoconfig:/data/configdb
        networks:
            - internal

    mongo-express:
        image: mongo-express:1.0.2
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: password
        networks:
            - internal

    redis:
        image: redis:7.2.4
        environment:
            ALLOW_EMPTY_PASSWORD: 'no'
            REDIS_EXTRA_FLAGS: '--maxmemory 250mb'
        command: >
            --requirepass password
        ports:
            - 6379:6379
        networks:
            - internal

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOST=redis
            - REDIS_PASSWORD=password
            - ADDRESS=0.0.0.0
        ports:
            - 8083:8081
        networks:
            - internal

    queue:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 8084:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
        volumes:
            - rabbitmq:/var/lib/rabbitmq

volumes:
    rabbitmq:
    postgres:
    mongodb:
    mongoconfig:

networks:
    internal:
